name: pull-request
on:
  pull_request:
    branches:
      - master
      - main

jobs:
  call-workflow:
    uses: rent-a-camel-idp/shared-workflows/.github/workflows/dotnet-ci.yaml@main
    with:
      app: ${{values.application.split(":")[1]}}